# Generated by Django 4.2.1 on 2023-06-15 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assesments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=255)),
                ("video_name", models.CharField(max_length=255)),
                ("video_desc", models.TextField()),
                ("video_url", models.URLField()),
                ("is_deleted", models.BooleanField(default=False)),
                ("status", models.IntegerField(default=1)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "test_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assesments.testrecord",
                    ),
                ),
            ],
            options={"db_table": "video_recommendation",},
        ),
        migrations.CreateModel(
            name="TestParagraph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("para_ee", models.TextField()),
                ("para_dp", models.TextField()),
                ("para_pa", models.TextField()),
                ("is_deleted", models.BooleanField(default=False)),
                ("status", models.IntegerField(default=1)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "test_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assesments.testrecord",
                    ),
                ),
            ],
            options={"db_table": "test_paragraph",},
        ),
    ]
