# Generated by Django 4.2.1 on 2023-06-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommendations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestVideoResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_id", models.CharField(max_length=100)),
                ("video_url", models.URLField()),
                ("video_title", models.CharField(max_length=200)),
                ("similarity_score", models.FloatField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={"db_table": "test_video_results",},
        ),
    ]
