# Generated by Django 4.2.1 on 2023-06-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommendations", "0002_testvideoresult"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testparagraph",
            name="test_record",
            field=models.CharField(max_length=100),
        ),
    ]
